config:
  send_anonymous_usage_stats: False

fal_test:
  target: staging
  outputs:
    staging:
      type: fal
      db_profile: db
    db:
      type: postgres
      host: localhost
      port: 5432
      user: pguser
      password: pass
      dbname: test
      schema: dbt_fal
      threads: 4
